name: OSSF Scorecard

on:
  push:
    branches:
      - main   # run only when pushing to main

permissions:
  # Needed for uploading the SARIF file
  security-events: write
  # Scorecard also needs read access to repo contents
  contents: read
  actions: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false   # set true only if you want results public in OpenSSF API

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
